In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

Importing Dataset

In [2]:
df = pd.read_csv('../artifacts/Restaurant_reviews.csv', encoding = "ISO-8859-1")

In [3]:
import os
print(os.getcwd())

C:\Users\hasitha\Desktop\review_sentiment\notebooks


In [4]:
file_path = "../artifacts/Restaurant reviews.csv"

In [5]:
file_path

'../artifacts/Restaurant reviews.csv'

In [6]:
print(os.listdir("../artifacts"))

['.ipynb_checkpoints', 'Restaurant_reviews.csv']


In [7]:
df

Restaurant              Reviewer  \
0      Beyond Flavours     Rusha Chakraborty   
1      Beyond Flavours  Anusha Tirumalaneedi   
2      Beyond Flavours       Ashok Shekhawat   
3      Beyond Flavours        Swapnil Sarkar   
4      Beyond Flavours                Dileep   
...                ...                   ...   
9995  Chinese Pavilion      Abhishek Mahajan   
9996  Chinese Pavilion        Sharad Agrawal   
9997  Chinese Pavilion             Ramandeep   
9998  Chinese Pavilion       Nayana Shanbhag   
9999  Chinese Pavilion      Bhargava Krishna   

                                                 Review Rating  \
0     The ambience was good, food was quite good . h...      5   
1     Ambience is too good for a pleasant evening. S...      5   
2     A must try.. great food great ambience. Thnx f...      5   
3     Soumen das and Arun was a great guy. Only beca...      5   
4     Food is good.we ordered Kodi drumsticks and ba...      5   
...                                                 ...    ...   
9995  Madhumathi Mahajan Well to start with nice cou...      3   
9996  This place has never disappointed us.. The foo...    4.5   
9997  Bad rating is mainly because of "Chicken Bone ...    1.5   
9998  I personally love and prefer Chinese Food. Had...      4   
9999  Checked in here to try some delicious chinese ...    3.5   

                          Metadata             Time  Pictures    7514  
0           1 Review , 2 Followers  5/25/2019 15:54         0  2447.0  
1          3 Reviews , 2 Followers  5/25/2019 14:20         0     NaN  
2          2 Reviews , 3 Followers  5/24/2019 22:54         0     NaN  
3            1 Review , 1 Follower  5/24/2019 22:11         0     NaN  
4          3 Reviews , 2 Followers  5/24/2019 21:37         0     NaN  
...                            ...              ...       ...     ...  
9995     53 Reviews , 54 Followers    6/5/2016 0:08         0     NaN  
9996      2 Reviews , 53 Followers   6/4/2016 22:01         0     NaN  
9997    65 Reviews , 423 Followers   6/3/2016 10:37         3     NaN  
9998    13 Reviews , 144 Followers  5/31/2016 17:22         0     NaN  
9999  472 Reviews , 1302 Followers  5/31/2016 16:41         6     NaN  

[10000 rows x 8 columns]

In [8]:
df.shape

(10000, 8)

Cleaning & Preparing Data

In [9]:
df = df.drop(columns=["Restaurant","Reviewer","Metadata","Time","Pictures"])

In [10]:
y = df["Rating"]
X = df.drop(columns=["Rating"])
X.shape

(10000, 2)

In [11]:
y = y.replace({'Like':3})

In [12]:
y.isnull().sum()

np.int64(38)

In [19]:
print(y.dtype)

object


In [13]:
y = pd.to_numeric(y)

In [14]:
y = y.fillna(y.median())

In [15]:
y

0       5.0
1       5.0
2       5.0
3       5.0
4       5.0
       ... 
9995    3.0
9996    4.5
9997    1.5
9998    4.0
9999    3.5
Name: Rating, Length: 10000, dtype: float64

In [16]:
for i in range(0,len(y)):
    y.iloc[i] = round(y.iloc[i],0)

In [17]:
for i in range(0,len(y)):
    if (y[i]>=3):
        y[i] = "Positive"
    else:
        y[i] = "Negative"

C:\Users\hasitha\AppData\Local\Temp\ipykernel_13136\1156208666.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Positive' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  y[i] = "Positive"


In [21]:
for i in range(0,len(y)):
    if (y[i]>=3):
        y[i] = 1
    else:
        y[i] = 0

In [22]:
y.unique()

array([0], dtype=object)

In [23]:
y.shape

(10000,)

Applying NLP Processes

In [25]:
!pip install nltk

  Using cached nltk-3.9.1-py3-none-any.whl.metadata (2.9 kB)
  Using cached click-8.1.8-py3-none-any.whl.metadata (2.3 kB)
  Using cached regex-2024.11.6-cp313-cp313-win_amd64.whl.metadata (41 kB)
  Using cached tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Using cached nltk-3.9.1-py3-none-any.whl (1.5 MB)
Using cached regex-2024.11.6-cp313-cp313-win_amd64.whl (273 kB)
Using cached click-8.1.8-py3-none-any.whl (98 kB)
Using cached tqdm-4.67.1-py3-none-any.whl (78 kB)


In [26]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(X)):
    review = re.sub('[^a-zA-Z]',' ', str(X['Review'][i]))
    review = review.lower() #Lowering the words is very imporatant in avoiding classifying same words as different words
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')] #Eleminating words that do not put much value in sentences.
    review = ' '.join(review) #Reconstructing sentences
    corpus.append(review)

For implementing LSTM goto direct LSTM Section Else Continue

In [28]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=9000) 
X = cv.fit_transform(corpus).toarray()

Train-Test Split

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [30]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(7500, 9000))

In [31]:
X_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(2500, 9000))

In [32]:
y_train

2967    0
700     0
3481    0
1621    0
800     0
       ..
9225    0
4859    0
3264    0
9845    0
2732    0
Name: Rating, Length: 7500, dtype: object

In [33]:
y_test

9394    0
898     0
2398    0
5906    0
2343    0
       ..
8764    0
4359    0
2041    0
1108    0
3332    0
Name: Rating, Length: 2500, dtype: object

In [34]:
y_train.value_counts()

Rating
0    7500
Name: count, dtype: int64

In [35]:
plt.pie(np.array([Y_train.value_counts()[0], Y_train.value_counts()[1]]), 
        labels=['positive', 'negative'])
plt.title('Class Distribution')
plt.show()

NameError: name 'plt' is not defined

In [36]:
pip install matplotlib

  Using cached matplotlib-3.10.1-cp313-cp313-win_amd64.whl.metadata (11 kB)
  Using cached contourpy-1.3.1-cp313-cp313-win_amd64.whl.metadata (5.4 kB)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
  Using cached fonttools-4.56.0-cp313-cp313-win_amd64.whl.metadata (103 kB)
  Using cached kiwisolver-1.4.8-cp313-cp313-win_amd64.whl.metadata (6.3 kB)
  Using cached pillow-11.1.0-cp313-cp313-win_amd64.whl.metadata (9.3 kB)
  Using cached pyparsing-3.2.1-py3-none-any.whl.metadata (5.0 kB)
Using cached matplotlib-3.10.1-cp313-cp313-win_amd64.whl (8.1 MB)
Using cached contourpy-1.3.1-cp313-cp313-win_amd64.whl (220 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.56.0-cp313-cp313-win_amd64.whl (2.2 MB)
Using cached kiwisolver-1.4.8-cp313-cp313-win_amd64.whl (71 kB)
Using cached pillow-11.1.0-cp313-cp313-win_amd64.whl (2.6 MB)
Using cached pyparsing-3.2.1-py3-none-any.whl (107 kB)
Note: you may need to restart the kernel to use updated packages.